[package]
name = "violet"
version = "0.1.0"
authors = ["uzushino <torattoria.mamiya@gmail.com>"]
edition = "2018"

[dependencies]
failure = "*"
comrak = "*"
mdcat = "*"
quick-js = "0.2.2"
syntect = "*"
pulldown-cmark = "*"
madato = "*"
clap = "*"
env_logger = "*"
termion = "*"
unicode-width = "0.1.5"
terminal_size = "*"
libc = "*"
redux-rs = "*"
actix-web = "*"
actix-rt = "*"
futures = "*"
linked-hash-map = "*"